name: Build and test app in NCS docker container

on:
  push:

jobs:
  build-and-test-in-docker:
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.99
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    steps:
      - name: Checkout repository with application
        uses: actions/checkout@v4
        with:
          path: bme680-ble-sensor

      - name: Prepare west project
        run: |
          west init -l bme680-ble-sensor
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: bme680-ble-sensor
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: bme680-ble-sensor/twister-out/**/zephyr/zephyr.hex

      # - name: Twister Tests
      #   working-directory: example-application
      #   run: |
      #     west twister -T tests -v --inline-logs --integration